version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      container_name: postgres
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: postgres-db
        POSTGRES_USER: user-postgres
        POSTGRES_PASSWORD: password-postgres
      ports:
       - 5432:5432
      restart: always
      networks:
        - postgres-network
